### ISSUE TITLE
Found a bug in Jenkins 2.x 

### ISSUE THREAD

**Issue by capricornxl** [SoftwareBuildService/log-file-filter-plugin#1]
Hi guys, Thank you for this plugin that provides such great features.  
Now, the version of Jenkins I am currently running is 2.173, when I configure "Log File Filter Global config"(Enable globally and Enable default regexp all checked) .
Then I configured some regular expressions I needed, and they all passed the test, However, when I restarted Jenkins, all the configuration in “Log File Filter Global config” was lost.
I tried to reconfigure it again and tried to restart Jenkins. This phenomenon reappears.Verify that my guess is correct.
This plugin is really great, so I have to use it, can you look at this problem?

**Comment by amandel** [comment]
Thanks for spotting this. Not sure when this functionality broke, I tend not to restart my Jenkins very often. Please check out https://github.com/jenkinsci/log-file-filter-plugin for updates.

**Comment by amandel** [comment]
Fixed with version 1.11 of the plugin
